In [1]:
import pickle
import numpy as np
import pandas as pd

In [2]:
popular_df = pd.read_pickle('popular.pkl')
pt  = pd.read_pickle('pt.pkl')
books  = pd.read_pickle('books.pkl')
similarity_scores  = pd.read_pickle('similarity_scores.pkl')

In [3]:
import pickle

# Replace 'filename.pkl' with the actual name of your pickle file
file_path = 'similarity_scores.pkl'

# Load the data from the pickle file
with open(file_path, 'rb') as file:
    data = pd.read_pickle(file)

# Print the loaded data
pd.set_option("display.max_columns", None)
pd.set_option("display.expand_frame_repr", False)
print(data)


[[1.         0.10255025 0.01220856 ... 0.12110367 0.07347567 0.04316046]
 [0.10255025 1.         0.2364573  ... 0.07446129 0.16773875 0.14263397]
 [0.01220856 0.2364573  1.         ... 0.04558758 0.04938579 0.10796119]
 ...
 [0.12110367 0.07446129 0.04558758 ... 1.         0.07085128 0.0196177 ]
 [0.07347567 0.16773875 0.04938579 ... 0.07085128 1.         0.10602962]
 [0.04316046 0.14263397 0.10796119 ... 0.0196177  0.10602962 1.        ]]


In [4]:
user_input = "1984"
index = np.where(pt.index == user_input)[0]
print(index)
if len(index) > 0:
    index = index[0]
    similar_items = sorted(enumerate(similarity_scores[index]), key=lambda x: x[1], reverse=True)[1:6]
    data = []

    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(temp_df.drop_duplicates('Book-Title')['Book-Title'].values)
        item.extend(temp_df.drop_duplicates('Book-Title')['Book-Author'].values)
        item.extend(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values)

        data.append(item)

    for item in data:
        print("Book Title:", item[0])
        print("Book Author:", item[1])
        print("Image URL:", item[2])
        print("=" * 50)
else:
    print(f"Book '{user_input}' not found in the index.")


[0]
Book Title: Animal Farm
Book Author: George Orwell
Image URL: http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg
Book Title: The Handmaid's Tale
Book Author: Margaret Atwood
Image URL: http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg
Book Title: Brave New World
Book Author: Aldous Huxley
Image URL: http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg
Book Title: The Vampire Lestat (Vampire Chronicles, Book II)
Book Author: ANNE RICE
Image URL: http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg
Book Title: The Hours : A Novel
Book Author: Michael Cunningham
Image URL: http://images.amazon.com/images/P/0312243022.01.MZZZZZZZ.jpg


In [5]:
def recommend(book_name):
    #index fetch
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x: x[1],reverse=True)[1:6]
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title']== pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    return data
    

In [6]:
recommend("The Da Vinci Code")

[['Angels &amp; Demons',
  'Dan Brown',
  'http://images.amazon.com/images/P/0671027360.01.MZZZZZZZ.jpg'],
 ['Touching Evil',
  'Kay Hooper',
  'http://images.amazon.com/images/P/0553583441.01.MZZZZZZZ.jpg'],
 ['Saving Faith',
  'David Baldacci',
  'http://images.amazon.com/images/P/0446608890.01.MZZZZZZZ.jpg'],
 ["The Sweet Potato Queens' Book of Love",
  'JILL CONNER BROWNE',
  'http://images.amazon.com/images/P/0609804138.01.MZZZZZZZ.jpg'],
 ['Middlesex: A Novel',
  'Jeffrey Eugenides',
  'http://images.amazon.com/images/P/0312422156.01.MZZZZZZZ.jpg']]

In [7]:
user_input = "The Da Vinci Code"
index = np.where(pt.index == user_input)[0][0]
similar_items = sorted(list(enumerate(similarity_scores[index])), key=lambda x: x[1], reverse=True)[1:6]
data = []
for i in similar_items:
    item = []
    temp_df = books[books['Book-Title'] == pt.index[i[0]]]
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))

    data.append(item)
print(data)

[['Angels &amp; Demons', 'Dan Brown', 'http://images.amazon.com/images/P/0671027360.01.MZZZZZZZ.jpg'], ['Touching Evil', 'Kay Hooper', 'http://images.amazon.com/images/P/0553583441.01.MZZZZZZZ.jpg'], ['Saving Faith', 'David Baldacci', 'http://images.amazon.com/images/P/0446608890.01.MZZZZZZZ.jpg'], ["The Sweet Potato Queens' Book of Love", 'JILL CONNER BROWNE', 'http://images.amazon.com/images/P/0609804138.01.MZZZZZZZ.jpg'], ['Middlesex: A Novel', 'Jeffrey Eugenides', 'http://images.amazon.com/images/P/0312422156.01.MZZZZZZZ.jpg']]
